@urlBase   = http://localhost:3000
@urlHealth = {{urlBase}}/health
@urlUser   = {{urlBase}}/users
@idUsuario = 424f9501-9020-4a46-846c-d999ad49342b

###
# Health check
GET {{urlHealth}}

###
# Obtener todos los usuarios
GET {{urlUser}}

###
# Crear un nuevo usuario (copiá el "id" de la respuesta y pegalo en @idUsuario)
POST {{urlUser}}
Content-Type: application/json

{
    "name": "juan123",
    "email": "juan@email.com",
    "password": "miPassword123",
    "role": "alumno"
}

###
# Obtener un usuario por id
GET {{urlUser}}/{{idUsuario}}

###
# Modificar un usuario (todos los campos)
PUT {{urlUser}}/{{idUsuario}}
Content-Type: application/json

{
    "name": "juan1234",
    "email": "juan.nuevo@email.com",
    "password": "miNuevoPassword123",
    "role": "profesor"
}

###
# Eliminar un usuario
DELETE {{urlUser}}/{{idUsuario}}
